feat:３の倍数の出力
mikan19/PHP-for pull request #1
Opened 2023-04-13 11:49 UTC by mikan19

**作業対象**

[作業をした教材のURL]　
[https://www.notion.so/for-767bcc350c124a89b973d92f92fbf005](url)

**作業詳細**

PHP基礎　for文の課題
for文で1~6までループさせ、$iが3の倍数の時だけ$iを出力するコードを書きました。

<img width="346" alt="スクリーンショット 2023-04-13 20 42 09" src="https://user-images.githubusercontent.com/128659635/231748671-19d46edc-1a59-4a37-8bcf-a830ab867086.png">

2023-04-14 07:51 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊

2023-04-14 07:51 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +for($i = 1 ; $i < 7 ; $i++){
今回もきれいなコードですね！！
これでも良いのですが、【1~6までループさせ、】とあるので、
【$i <= 6】のが良いとおもいます！😊

せっかくなので、修正してみましょう！！🙆😳

2023-04-15 09:57 UTC, mikan19 commented
【$i < 7】を【$i <= 6】に修正しました。ご確認のほどよろしくお願いいたします。
![2023-04-15 18 53のイメージ](https://user-images.githubusercontent.com/128659635/232207032-49a80eb6-3f87-42e6-aa96-6e5ac61b965d.jpg)

2023-04-17 00:01 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
プルリクの修正依頼からの修正作業もなんなくできていて素晴らしいです！

mergeいただけると助かります！🙆🙋😊

2023-04-17 00:36 UTC, merged